ports:
  - port: 3000-8999
image:
  file: .gitpod.Dockerfile
tasks:
  - init: echo "Replace me with a build script for the project."
    command: mkdir -p /workspace/data && mongod --dbpath /workspace/data &
